# Generated by Django 4.2.7 on 2023-11-28 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=200)),
                ('sender_origin', models.CharField(max_length=200)),
                ('froms', models.CharField(max_length=200)),
                ('tos', models.CharField(max_length=200)),
                ('item_description', models.CharField(max_length=200)),
                ('reciver_name', models.CharField(max_length=200)),
                ('reciver_email', models.EmailField(max_length=200)),
                ('reciver_address', models.CharField(max_length=200)),
                ('reciver_phone', models.CharField(max_length=200)),
                ('Weight_And_Dimension', models.CharField(max_length=200)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
