# Generated by Django 4.2.7 on 2023-11-28 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='item_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='quote',
            name='reciver_address',
            field=models.TextField(),
        ),
    ]
